[workspace]
resolver = "2"

members = [
  "glean-core",
  "glean-core/rlb",
  "glean-core/bundle",
  "glean-core/bundle-android",
  "glean-core/build",
  "samples/rust",
  "tools/embedded-uniffi-bindgen",
]

default-members = [
  "glean-core",
  "tools/embedded-uniffi-bindgen",
]

[profile.release]
opt-level = "s"
debug = false
lto = true

[patch.crates-io]
uniffi = { path = "../uniffi-rs/uniffi" }
uniffi_bindgen = { path = "../uniffi-rs/uniffi_bindgen" }
